import { generateModelsFile, generateSeedDataFile, generateStorageFile } from "./scaffoldData";
import { generateComponentFiles, generatePages } from "./scaffoldPages";
import {
  generateGlobalsCss,
  generateLayout,
  generateNextConfig,
  generatePackageJson,
  generateTsConfig,
} from "./scaffoldRoot";
import { readmeToMarkdown } from "./markdown";
import type { ProjectMap, ScaffoldFile } from "./types";

function generateNextEnv(): ScaffoldFile {
  return {
    path: "next-env.d.ts",
    contents:
      '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by Next.js and shouldn\'t be edited.\n',
  };
}

function generateGitignore(): ScaffoldFile {
  return {
    path: ".gitignore",
    contents: "node_modules\n.next\nnpm-debug.log*\n.env*\n",
  };
}

function generateReadmeFile(map: ProjectMap): ScaffoldFile {
  return { path: "README.md", contents: `${readmeToMarkdown(map.readme)}\n` };
}

/**
 * Generate a complete, runnable Next.js project from a ProjectMap: real
 * pages and components, TypeScript data models, a localStorage-backed data
 * layer with seed records, and the standard project files needed to
 * `npm install && npm run dev` it.
 */
export function generateScaffold(map: ProjectMap): ScaffoldFile[] {
  return [
    generatePackageJson(map.spec.name),
    generateTsConfig(),
    generateNextConfig(),
    generateNextEnv(),
    generateGitignore(),
    generateReadmeFile(map),
    generateLayout(map.spec.name, map.screens),
    generateGlobalsCss(),
    ...generatePages(map.screens, map.components, map.dataModels),
    ...generateComponentFiles(map.components, map.dataModels),
    generateModelsFile(map.dataModels),
    generateStorageFile(),
    generateSeedDataFile(map.dataModels),
  ];
}
